services:
    backend:
        build: .
        volumes:
            - .:/usr/src/app/
        ports:
            - '8000:8000'
        env_file:
            - ./talatask/.env
        restart: unless-stopped
        depends_on:
            - db

    db:
        image: postgres:latest
        container_name: db
        hostname: db
        restart: unless-stopped
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: talatask_db
            POSTGRES_USER: talatask
            POSTGRES_PASSWORD: talatask_passwd
        volumes:
            - postgresql-data:/var/lib/postgresql/data

volumes:
    postgresql-data:
        driver: local
