# Generated by Django 5.1.3 on 2024-11-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_schedule_last_assignment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.skill'),
        ),
    ]
